### ISSUE TITLE
Crash while adding a bookmark

### ISSUE THREAD

**Issue by mertceyhan** [icanteach/droidhub#33]
Adding bookmark without login causes a crash, you can find the crash log below;

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.icanteach.apps.android.droidhub, PID: 3241
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at co.icanteach.apps.android.droidhub.features.bookmark.AddToBookmarkUseCase.addToBookmark(AddToBookmarkUseCase.kt:21)
        at co.icanteach.apps.android.droidhub.features.bookmark.AddToBookmarkUseCase$addToBookmark$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@42ebf8, Dispatchers.Main.immediate]

```

**Comment by mertceyhan** [comment]
Could be a solution;
`val userBookmarks = firestore.collection(USERS_BOOKMARKS).document((user?.id ?: 0).toString())
`

**Comment by muratcanbur** [comment]
You got me. 
Since I will create a feature task showing that user should login :)
